version: "3"
services:
  buerokratt_chatbot:
    container_name: buerokratt_chatbot
    build:
      context: .
      dockerfile: Dockerfile.dev
      target: web
    # entrypoint: "/opt/buerokratt-chatbot/rebuild.sh"
    ports:
      - '3001:3001'
