name: Playwright Tests

on:
  pull_request:
    branches:
      - dev
    paths:
      - 'GUI/**'
  
  push:
    branches:
      - dev
    paths:
      - 'GUI/README.md'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Install Playwright
        run: npx playwright install

# To run all
#       - name: Run Playwright tests
#         run: npx playwright test GUI/tests/admin/landingPage

# To run only one
#      - name: Run Playwright tests
#        run: npx playwright test GUI/tests/admin/landingPage/visibility.spec.js

      - name: Run Playwright tests
        run: npx playwright test GUI/tests/admin/landingPage/functionality.spec.js
