name: Trigger Playwright Tests
on:
  project_card:
    types: [moved] # When a task is moved in the project board

jobs:
  trigger-tests:
    runs-on: ubuntu-latest
    if: github.event.project_card.column_name == 'Acceptance Testing'
    steps:
      - name: Fetch task details
        run: |
          TASK_URL=${{ github.event.project_card.content_url }}
          TASK_DESCRIPTION=$(curl -s $TASK_URL | jq -r '.body')
          TASK_TITLE=$(curl -s $TASK_URL | jq -r '.title')

          # Send task details to the Playwright test repo
          REPO="owner/playwright-repo"
          curl -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/$REPO/dispatches \
            -d '{"event_type": "run-tests", "client_payload": {"task_description": "'$TASK_DESCRIPTION'", "task_title": "'$TASK_TITLE'"}}'
